leftnav:
- identifier: 89dab3cd-a2de-f3f8-2d0a-0fbe5bb55f17
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: external-22f66204d5704061b685c9728f2c92b2
  name: Online Publication
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+6.036+1T2019/about
  weight: 1000
